# Generated by Django 5.2.9 on 2025-12-16 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIFeedback',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_id', models.BigIntegerField()),
                ('candidate_id', models.BigIntegerField()),
                ('decision', models.CharField(blank=True, max_length=50, null=True)),
                ('feedback', models.CharField(max_length=50)),
                ('visual_score', models.FloatField(default=0.0)),
                ('text_score', models.FloatField(default=0.0)),
                ('final_score', models.FloatField(default=0.0)),
                ('match_method', models.CharField(blank=True, max_length=50, null=True)),
                ('active_weights', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_feedback',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='ClusterConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('weight_visual', models.FloatField(default=0.6)),
                ('weight_text', models.FloatField(default=0.4)),
                ('threshold_visual_rescue', models.FloatField(default=0.15)),
                ('threshold_text_rescue', models.FloatField(default=0.95)),
                ('threshold_hybrid', models.FloatField(default=0.68)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_note', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'cluster_config',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('suggested_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('profit_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('product_type', models.CharField(blank=True, max_length=50, null=True)),
                ('url_image_s3', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('store_name', models.CharField(blank=True, max_length=255, null=True)),
                ('plan_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('reputation_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'suppliers',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'warehouses',
            },
        ),
        migrations.CreateModel(
            name='ProductEmbedding',
            fields=[
                ('product', models.OneToOneField(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.product')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_embeddings',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, db_column='supplier_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.supplier'),
        ),
        migrations.CreateModel(
            name='UniqueProductCluster',
            fields=[
                ('cluster_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_competitors', models.IntegerField(default=1)),
                ('average_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('saturation_score', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('representative_product', models.ForeignKey(blank=True, db_column='representative_product_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='core.product')),
            ],
            options={
                'db_table': 'unique_product_clusters',
            },
        ),
        migrations.CreateModel(
            name='ProductStockLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_qty', models.IntegerField()),
                ('snapshot_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('warehouse', models.ForeignKey(db_column='warehouse_id', on_delete=django.db.models.deletion.CASCADE, to='core.warehouse')),
            ],
            options={
                'db_table': 'product_stock_log',
            },
        ),
        migrations.CreateModel(
            name='ProductClusterMembership',
            fields=[
                ('product', models.OneToOneField(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cluster_membership', serialize=False, to='core.product')),
                ('match_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('match_method', models.CharField(blank=True, max_length=50, null=True)),
                ('cluster', models.ForeignKey(db_column='cluster_id', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.uniqueproductcluster')),
            ],
            options={
                'db_table': 'product_cluster_membership',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
            options={
                'db_table': 'product_categories',
                'unique_together': {('product', 'category')},
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-profit_margin', '-created_at'], name='products_profit__f9ffbe_idx'),
        ),
    ]
