# Generated by Django 6.0 on 2026-01-24 01:52

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIFeedback',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_id', models.BigIntegerField()),
                ('candidate_id', models.BigIntegerField()),
                ('decision', models.CharField(blank=True, max_length=50, null=True)),
                ('feedback', models.CharField(max_length=50)),
                ('visual_score', models.FloatField(default=0.0)),
                ('text_score', models.FloatField(default=0.0)),
                ('final_score', models.FloatField(default=0.0)),
                ('match_method', models.CharField(blank=True, max_length=50, null=True)),
                ('active_weights', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_feedback',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('semantic_coherence_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('intent_validation_status', models.CharField(default='PENDING', max_length=50)),
                ('taxonomy_type', models.CharField(default='UNKNOWN', max_length=50)),
                ('suggested_parent', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='ClusterConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('weight_visual', models.FloatField(default=0.6)),
                ('weight_text', models.FloatField(default=0.4)),
                ('threshold_visual_rescue', models.FloatField(default=0.15)),
                ('threshold_text_rescue', models.FloatField(default=0.95)),
                ('threshold_hybrid', models.FloatField(default=0.68)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_note', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'cluster_config',
            },
        ),
        migrations.CreateModel(
            name='ClusterDecisionLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.BigIntegerField()),
                ('candidate_id', models.BigIntegerField()),
                ('title_a', models.TextField(blank=True, null=True)),
                ('title_b', models.TextField(blank=True, null=True)),
                ('image_a', models.TextField(blank=True, null=True)),
                ('image_b', models.TextField(blank=True, null=True)),
                ('visual_score', models.FloatField(blank=True, null=True)),
                ('text_score', models.FloatField(blank=True, null=True)),
                ('final_score', models.FloatField(blank=True, null=True)),
                ('decision', models.CharField(blank=True, max_length=50, null=True)),
                ('match_method', models.CharField(blank=True, max_length=50, null=True)),
                ('active_weights', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'db_table': 'cluster_decision_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ConceptWeights',
            fields=[
                ('concept', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('weight_visual', models.FloatField(default=0.6)),
                ('weight_text', models.FloatField(default=0.4)),
                ('threshold_hybrid', models.FloatField(default=0.68)),
                ('similarity_threshold_direct', models.FloatField(default=0.8)),
                ('similarity_threshold_indirect', models.FloatField(default=0.65)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'concept_weights',
            },
        ),
        migrations.CreateModel(
            name='DomainReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('is_shopify', models.BooleanField(blank=True, null=True)),
                ('shopify_likely_score', models.FloatField(default=0.0)),
                ('shopify_likely_reasons', models.JSONField(blank=True, default=dict)),
                ('shopify_last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('shopify_cache_expires_at', models.DateTimeField(blank=True, null=True)),
                ('pixel_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True)),
                ('detected_apps', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True)),
                ('has_active_ads', models.BooleanField(default=False)),
                ('ads_last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('ads_cache_expires_at', models.DateTimeField(blank=True, null=True)),
                ('ads_library_url', models.URLField(blank=True, max_length=500, null=True)),
                ('ads_count_recent', models.IntegerField(default=0)),
                ('ads_evidence', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'domain_reputation',
            },
        ),
        migrations.CreateModel(
            name='FutureEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('prep_days', models.IntegerField(default=30)),
                ('keywords', models.TextField(help_text='Keywords base para generar el vector')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'future_events',
            },
        ),
        migrations.CreateModel(
            name='MarketAnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('search_fingerprint', models.JSONField(default=dict)),
                ('candidates_found_raw', models.IntegerField(default=0)),
                ('shopify_likely_candidates_count', models.IntegerField(default=0)),
                ('candidates_processed', models.IntegerField(default=0)),
                ('direct_competitors_count', models.IntegerField(default=0)),
                ('indirect_competitors_count', models.IntegerField(default=0)),
                ('competitors_with_ads', models.IntegerField(default=0)),
                ('supplier_saturation_score', models.FloatField(default=0.0)),
                ('market_saturation_score', models.FloatField(default=0.0)),
                ('final_score', models.FloatField(default=0.0)),
                ('audit_log', models.JSONField(blank=True, default=list)),
                ('market_state', models.CharField(default='PENDING', max_length=50)),
            ],
            options={
                'db_table': 'market_analysis_reports',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('suggested_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('profit_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('product_type', models.CharField(blank=True, max_length=50, null=True)),
                ('url_image_s3', models.TextField(blank=True, null=True)),
                ('taxonomy_concept', models.CharField(blank=True, max_length=255, null=True)),
                ('taxonomy_industry', models.CharField(blank=True, max_length=255, null=True)),
                ('taxonomy_level', models.CharField(blank=True, max_length=50, null=True)),
                ('source_platform', models.CharField(blank=True, default='dropi', max_length=50, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('store_name', models.CharField(blank=True, max_length=255, null=True)),
                ('plan_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('reputation_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'suppliers',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'warehouses',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(blank=True, default='', max_length=120)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('CLIENT', 'Client')], default='CLIENT', max_length=10)),
                ('subscription_tier', models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], default='BRONZE', max_length=10)),
                ('subscription_active', models.BooleanField(default=False)),
                ('execution_time', models.TimeField(blank=True, help_text='Hora diaria para ejecutar el workflow de reportes (formato HH:MM)', null=True)),
                ('dropi_email', models.EmailField(blank=True, help_text='Email de la cuenta Dropi principal', max_length=255, null=True)),
                ('dropi_password', models.CharField(blank=True, help_text='Password de la cuenta Dropi (string simple, no encriptado)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DropiAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='default', max_length=50)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropi_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dropi_accounts',
            },
        ),
        migrations.CreateModel(
            name='CompetitorFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_found', models.URLField(max_length=1000)),
                ('title_detected', models.CharField(blank=True, max_length=500)),
                ('price_detected', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('visual_similarity', models.FloatField(null=True)),
                ('match_type', models.CharField(max_length=20)),
                ('domain_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.domainreputation')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='core.marketanalysisreport')),
            ],
            options={
                'db_table': 'competitor_findings',
            },
        ),
        migrations.CreateModel(
            name='MarketplaceFeedback',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('marketplace', models.CharField(max_length=50)),
                ('feedback_type', models.CharField(max_length=20)),
                ('text_content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('posted_at', models.DateField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='core.category')),
            ],
            options={
                'db_table': 'marketplace_feedback',
            },
        ),
        migrations.CreateModel(
            name='OrderReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_phone', models.CharField(db_index=True, help_text='Número de teléfono de la orden', max_length=50)),
                ('order_id', models.CharField(blank=True, help_text='ID de la orden en Dropi', max_length=100, null=True)),
                ('tracking_number', models.CharField(blank=True, help_text='Número de guía / Tracking', max_length=100, null=True)),
                ('status', models.CharField(choices=[('proximo_a_reportar', 'Próximo a Reportar'), ('reportado', 'Reportado'), ('error', 'Error'), ('no_encontrado', 'No Encontrado'), ('already_has_case', 'Ya Tiene Caso'), ('cannot_generate_yet', 'No Se Puede Generar Aún'), ('in_movement', 'En Movimiento')], default='proximo_a_reportar', max_length=50)),
                ('report_generated', models.BooleanField(default=False, help_text='True si el reporte se generó exitosamente')),
                ('customer_name', models.CharField(blank=True, help_text='Nombre del cliente', max_length=255, null=True)),
                ('product_name', models.TextField(blank=True, help_text='Nombre del producto vinculado a la orden', null=True)),
                ('order_state', models.CharField(blank=True, help_text='Estado actual de la orden en Dropi', max_length=100, null=True)),
                ('days_since_order', models.IntegerField(blank=True, help_text='Días transcurridos desde la orden (del CSV)', null=True)),
                ('next_attempt_time', models.DateTimeField(blank=True, help_text='Próximo intento (para estados que requieren espera)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_reports',
            },
        ),
        migrations.CreateModel(
            name='ProductClusterMembership',
            fields=[
                ('product', models.OneToOneField(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cluster_membership', serialize=False, to='core.product')),
                ('match_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('match_method', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'product_cluster_membership',
            },
        ),
        migrations.CreateModel(
            name='ProductEmbedding',
            fields=[
                ('product', models.OneToOneField(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.product')),
                ('embedding_visual', pgvector.django.vector.VectorField(blank=True, dimensions=1152, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_embeddings',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
            options={
                'db_table': 'product_categories',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, db_column='supplier_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.supplier'),
        ),
        migrations.CreateModel(
            name='UniqueProductCluster',
            fields=[
                ('cluster_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_competitors', models.IntegerField(default=1)),
                ('average_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('saturation_score', models.CharField(blank=True, max_length=20, null=True)),
                ('concept_name', models.CharField(blank=True, max_length=255, null=True)),
                ('visual_centroid', pgvector.django.vector.VectorField(blank=True, dimensions=1152, null=True)),
                ('visual_medoid_1', pgvector.django.vector.VectorField(blank=True, dimensions=1152, null=True)),
                ('visual_medoid_2', pgvector.django.vector.VectorField(blank=True, dimensions=1152, null=True)),
                ('visual_medoid_3', pgvector.django.vector.VectorField(blank=True, dimensions=1152, null=True)),
                ('medoid_meta', models.JSONField(blank=True, default=dict)),
                ('analysis_level', models.IntegerField(default=0)),
                ('is_discarded', models.BooleanField(default=False)),
                ('discard_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('is_candidate', models.BooleanField(default=False)),
                ('trend_score', models.IntegerField(default=0)),
                ('search_volume_estimate', models.IntegerField(blank=True, null=True)),
                ('seasonality_flag', models.CharField(blank=True, max_length=50, null=True)),
                ('market_avg_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('potential_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('market_saturation_level', models.CharField(blank=True, max_length=20, null=True)),
                ('market_opportunity_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('taxonomy_type', models.CharField(default='UNKNOWN', max_length=50)),
                ('dropi_competition_tier', models.CharField(blank=True, default='LOW', max_length=20, null=True)),
                ('validation_log', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('representative_product', models.ForeignKey(blank=True, db_column='representative_product_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='core.product')),
            ],
            options={
                'db_table': 'unique_product_clusters',
            },
        ),
        migrations.CreateModel(
            name='MarketIntelligenceLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=50)),
                ('data_point', models.CharField(max_length=100)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_numeric', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('embedding_context', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('snapshot_at', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.ForeignKey(blank=True, db_column='cluster_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_logs', to='core.uniqueproductcluster')),
            ],
            options={
                'db_table': 'market_intelligence_logs',
            },
        ),
        migrations.AddField(
            model_name='marketanalysisreport',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_reports', to='core.uniqueproductcluster'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=120)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('CLIENT', 'Client')], default='CLIENT', max_length=10)),
                ('subscription_tier', models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], default='BRONZE', max_length=10)),
                ('subscription_active', models.BooleanField(default=False)),
                ('execution_time', models.TimeField(blank=True, help_text='Hora diaria para ejecutar el workflow de reportes (formato HH:MM)', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dropi_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('dropi_password', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='ProductStockLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_qty', models.IntegerField()),
                ('snapshot_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('warehouse', models.ForeignKey(db_column='warehouse_id', on_delete=django.db.models.deletion.CASCADE, to='core.warehouse')),
            ],
            options={
                'db_table': 'product_stock_log',
            },
        ),
        migrations.CreateModel(
            name='WorkflowProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('step1_running', 'Paso 1: Descargando Reportes'), ('step1_completed', 'Paso 1: Completado'), ('step2_running', 'Paso 2: Comparando Reportes'), ('step2_completed', 'Paso 2: Completado'), ('step3_running', 'Paso 3: Reportando CAS'), ('step3_completed', 'Paso 3: Completado'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=50)),
                ('current_message', models.TextField(blank=True, help_text='Mensaje actual del progreso', null=True)),
                ('messages', models.JSONField(default=list, help_text='Lista de mensajes de progreso')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('step1_completed_at', models.DateTimeField(blank=True, null=True)),
                ('step2_completed_at', models.DateTimeField(blank=True, null=True)),
                ('step3_completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflow_progress',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_usernam_baeb4b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'subscription_tier'], name='users_role_e64af6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['subscription_active'], name='users_subscri_b7c731_idx'),
        ),
        migrations.AddIndex(
            model_name='dropiaccount',
            index=models.Index(fields=['user', 'is_default'], name='dropi_accou_user_id_fab244_idx'),
        ),
        migrations.AddIndex(
            model_name='dropiaccount',
            index=models.Index(fields=['email'], name='dropi_accou_email_fe7f23_idx'),
        ),
        migrations.AddConstraint(
            model_name='dropiaccount',
            constraint=models.UniqueConstraint(fields=('user', 'label'), name='uniq_dropi_account_label_per_user'),
        ),
        migrations.AddIndex(
            model_name='competitorfinding',
            index=models.Index(fields=['report', 'match_type'], name='competitor__report__84587c_idx'),
        ),
        migrations.AddIndex(
            model_name='orderreport',
            index=models.Index(fields=['user', 'order_phone'], name='order_repor_user_id_35b043_idx'),
        ),
        migrations.AddIndex(
            model_name='orderreport',
            index=models.Index(fields=['user', 'status'], name='order_repor_user_id_1b566b_idx'),
        ),
        migrations.AddIndex(
            model_name='orderreport',
            index=models.Index(fields=['user', 'report_generated'], name='order_repor_user_id_98327c_idx'),
        ),
        migrations.AddIndex(
            model_name='orderreport',
            index=models.Index(fields=['order_phone'], name='order_repor_order_p_fc1c49_idx'),
        ),
        migrations.AddIndex(
            model_name='orderreport',
            index=models.Index(fields=['next_attempt_time'], name='order_repor_next_at_0f3ed9_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderreport',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['reportado', 'proximo_a_reportar'])), fields=('user', 'order_phone'), name='unique_active_report_per_order'),
        ),
        migrations.AddField(
            model_name='productclustermembership',
            name='cluster',
            field=models.ForeignKey(db_column='cluster_id', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.uniqueproductcluster'),
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('product', 'category')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-profit_margin', '-created_at'], name='products_profit__f9ffbe_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_id'], name='products_product_c3fbc6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['supplier'], name='products_supplie_1396c7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('product_id', 'supplier')},
        ),
        migrations.AddIndex(
            model_name='workflowprogress',
            index=models.Index(fields=['user', 'status'], name='workflow_pr_user_id_810eed_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowprogress',
            index=models.Index(fields=['user', 'started_at'], name='workflow_pr_user_id_76a060_idx'),
        ),
    ]
