# Generated by Django 6.0 on 2026-01-24 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportBatch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('account_email', models.EmailField(help_text='Email de la cuenta Dropi de donde vino este reporte', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='SUCCESS', max_length=50)),
                ('total_records', models.IntegerField(default=0, help_text='Total de filas leídas del Excel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lote de Reporte',
                'verbose_name_plural': 'Lotes de Reportes',
                'db_table': 'report_batches',
            },
        ),
        migrations.CreateModel(
            name='RawOrderSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dropi_order_id', models.CharField(db_index=True, help_text='Columna: ID', max_length=100)),
                ('shopify_order_id', models.CharField(blank=True, help_text='Columna: NUMERO DE PEDIDO DE TIENDA', max_length=100, null=True)),
                ('guide_number', models.CharField(blank=True, help_text='Columna: NÚMERO GUIA', max_length=100, null=True)),
                ('current_status', models.CharField(db_index=True, help_text='Columna: ESTATUS', max_length=100)),
                ('carrier', models.CharField(blank=True, help_text='Columna: TRANSPORTADORA', max_length=100, null=True)),
                ('customer_name', models.CharField(blank=True, help_text='Columna: NOMBRE CLIENTE', max_length=255, null=True)),
                ('customer_phone', models.CharField(blank=True, db_index=True, help_text='Columna: TELÉFONO', max_length=50, null=True)),
                ('address', models.TextField(blank=True, help_text='Columna: DIRECCION', null=True)),
                ('city', models.CharField(blank=True, help_text='Columna: CIUDAD DESTINO', max_length=100, null=True)),
                ('department', models.CharField(blank=True, help_text='Columna: DEPARTAMENTO DESTINO', max_length=100, null=True)),
                ('product_name', models.TextField(blank=True, help_text='Columna: PRODUCTO', null=True)),
                ('quantity', models.IntegerField(default=1, help_text='Columna: CANTIDAD')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Columna: TOTAL DE LA ORDEN', max_digits=12, null=True)),
                ('order_date', models.DateField(blank=True, help_text='Columna: FECHA (convertida a Date)', null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.reportbatch')),
            ],
            options={
                'db_table': 'raw_order_snapshots',
            },
        ),
        migrations.AddIndex(
            model_name='reportbatch',
            index=models.Index(fields=['user', 'created_at'], name='report_batc_user_id_dfa1a8_idx'),
        ),
        migrations.AddIndex(
            model_name='reportbatch',
            index=models.Index(fields=['account_email'], name='report_batc_account_c1363f_idx'),
        ),
        migrations.AddIndex(
            model_name='rawordersnapshot',
            index=models.Index(fields=['dropi_order_id'], name='raw_order_s_dropi_o_83fc72_idx'),
        ),
        migrations.AddIndex(
            model_name='rawordersnapshot',
            index=models.Index(fields=['current_status'], name='raw_order_s_current_ff1c3f_idx'),
        ),
        migrations.AddIndex(
            model_name='rawordersnapshot',
            index=models.Index(fields=['batch', 'current_status'], name='raw_order_s_batch_i_bbeda9_idx'),
        ),
    ]
