# Generated by Django 6.0 on 2026-01-24 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reportbatch_rawordersnapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreport',
            name='days_since_order',
            field=models.IntegerField(blank=True, help_text='DÃ\xadas transcurridos desde la orden (del CSV)', null=True),
        ),
        migrations.AlterField(
            model_name='orderreport',
            name='next_attempt_time',
            field=models.DateTimeField(blank=True, help_text='PrÃ³ximo intento (para estados que requieren espera)', null=True),
        ),
        migrations.AlterField(
            model_name='orderreport',
            name='order_phone',
            field=models.CharField(db_index=True, help_text='NÃºmero de telÃ©fono de la orden', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderreport',
            name='report_generated',
            field=models.BooleanField(default=False, help_text='True si el reporte se generÃ³ exitosamente'),
        ),
        migrations.AlterField(
            model_name='orderreport',
            name='status',
            field=models.CharField(choices=[('proximo_a_reportar', 'PrÃ³ximo a Reportar'), ('reportado', 'Reportado'), ('error', 'Error'), ('no_encontrado', 'No Encontrado'), ('already_has_case', 'Ya Tiene Caso'), ('cannot_generate_yet', 'No Se Puede Generar AÃºn'), ('in_movement', 'En Movimiento')], default='proximo_a_reportar', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderreport',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='NÃºmero de guÃ\xada / Tracking', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rawordersnapshot',
            name='customer_phone',
            field=models.CharField(blank=True, db_index=True, help_text='Columna: TELÃ‰FONO', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rawordersnapshot',
            name='guide_number',
            field=models.CharField(blank=True, help_text='Columna: NÃšMERO GUIA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reportbatch',
            name='total_records',
            field=models.IntegerField(default=0, help_text='Total de filas leÃ\xaddas del Excel'),
        ),
        migrations.CreateModel(
            name='OrderMovementReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('days_since_order', models.IntegerField(default=0, help_text='Días desde que se creó la orden hasta hoy')),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(help_text='El reporte donde se detectó (HOY)', on_delete=django.db.models.deletion.CASCADE, related_name='stagnant_orders', to='core.reportbatch')),
                ('snapshot', models.ForeignKey(help_text='La foto de la orden hoy', on_delete=django.db.models.deletion.CASCADE, related_name='stagnant_findings', to='core.rawordersnapshot')),
            ],
            options={
                'verbose_name': 'Orden Sin Movimiento',
                'verbose_name_plural': 'Órdenes Sin Movimiento',
                'db_table': 'order_movement_reports',
                'indexes': [models.Index(fields=['batch', 'is_resolved'], name='order_movem_batch_i_1c1942_idx')],
            },
        ),
    ]
