# Generated by Django on 2025-12-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_futureevent_category_description_category_embedding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptWeights',
            fields=[
                ('concept', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('weight_visual', models.FloatField(default=0.6)),
                ('weight_text', models.FloatField(default=0.4)),
                ('threshold_hybrid', models.FloatField(default=0.68)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'concept_weights',
            },
        ),
    ]
