# Generated by Django 5.2.9 on 2025-12-28 19:21

import core.models
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_conceptweights'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_found', models.URLField(max_length=1000)),
                ('title_detected', models.CharField(blank=True, max_length=500)),
                ('price_detected', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('visual_similarity', models.FloatField(null=True)),
                ('match_type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'competitor_findings',
            },
        ),
        migrations.CreateModel(
            name='DomainReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('is_shopify', models.BooleanField(blank=True, null=True)),
                ('shopify_likely_score', models.FloatField(default=0.0)),
                ('shopify_likely_reasons', models.JSONField(blank=True, default=dict)),
                ('shopify_last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('shopify_cache_expires_at', models.DateTimeField(blank=True, null=True)),
                ('pixel_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('detected_apps', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('has_active_ads', models.BooleanField(default=False)),
                ('ads_last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('ads_cache_expires_at', models.DateTimeField(blank=True, null=True)),
                ('ads_library_url', models.URLField(blank=True, max_length=500, null=True)),
                ('ads_count_recent', models.IntegerField(default=0)),
                ('ads_evidence', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'domain_reputation',
            },
        ),
        migrations.CreateModel(
            name='MarketAnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('search_fingerprint', models.JSONField(default=dict)),
                ('candidates_found_raw', models.IntegerField(default=0)),
                ('shopify_likely_candidates_count', models.IntegerField(default=0)),
                ('candidates_processed', models.IntegerField(default=0)),
                ('direct_competitors_count', models.IntegerField(default=0)),
                ('indirect_competitors_count', models.IntegerField(default=0)),
                ('competitors_with_ads', models.IntegerField(default=0)),
                ('supplier_saturation_score', models.FloatField(default=0.0)),
                ('market_saturation_score', models.FloatField(default=0.0)),
                ('final_score', models.FloatField(default=0.0)),
                ('market_state', models.CharField(default='PENDING', max_length=50)),
            ],
            options={
                'db_table': 'market_analysis_reports',
            },
        ),
        migrations.AddField(
            model_name='conceptweights',
            name='similarity_threshold_direct',
            field=models.FloatField(default=0.8),
        ),
        migrations.AddField(
            model_name='conceptweights',
            name='similarity_threshold_indirect',
            field=models.FloatField(default=0.65),
        ),
        migrations.AddField(
            model_name='uniqueproductcluster',
            name='medoid_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='uniqueproductcluster',
            name='visual_centroid',
            field=core.models.VectorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uniqueproductcluster',
            name='visual_medoid_1',
            field=core.models.VectorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uniqueproductcluster',
            name='visual_medoid_2',
            field=core.models.VectorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uniqueproductcluster',
            name='visual_medoid_3',
            field=core.models.VectorField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('product_id', 'supplier')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_id'], name='products_product_c3fbc6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['supplier'], name='products_supplie_1396c7_idx'),
        ),
        migrations.AddField(
            model_name='competitorfinding',
            name='domain_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.domainreputation'),
        ),
        migrations.AddField(
            model_name='marketanalysisreport',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_reports', to='core.uniqueproductcluster'),
        ),
        migrations.AddField(
            model_name='competitorfinding',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='core.marketanalysisreport'),
        ),
        migrations.AddIndex(
            model_name='competitorfinding',
            index=models.Index(fields=['report', 'match_type'], name='competitor__report__84587c_idx'),
        ),
    ]
