# Generated by Django 5.2.9 on 2025-12-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_competitorfinding_domainreputation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketanalysisreport',
            name='audit_log',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
