# Generated by Django 6.0 on 2026-01-21 02:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_category_embedding_alter_futureevent_embedding_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CLIENT', 'Client')], default='CLIENT', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_plan',
            field=models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro'), ('ADMIN', 'Admin')], default='FREE', max_length=10),
        ),
        migrations.CreateModel(
            name='DropiAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='default', max_length=50)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropi_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dropi_accounts',
                'indexes': [models.Index(fields=['user', 'is_default'], name='dropi_accou_user_id_fab244_idx'), models.Index(fields=['email'], name='dropi_accou_email_fe7f23_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'label'), name='uniq_dropi_account_label_per_user')],
            },
        ),
    ]
