# Generated by GPT-5.2 on 2026-01-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_user_subscriptions_and_dropi_accounts"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="subscription_plan",
            new_name="subscription_tier",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="subscription_tier",
            field=models.CharField(
                choices=[
                    ("BRONZE", "Bronze"),
                    ("SILVER", "Silver"),
                    ("GOLD", "Gold"),
                    ("PLATINUM", "Platinum"),
                ],
                default="BRONZE",
                max_length=10,
            ),
        ),
    ]

