# Generated by GPT-5.2 on 2026-01-21

from django.db import migrations


def set_admin_role_for_superusers(apps, schema_editor):
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("core", "UserProfile")

    for u in User.objects.filter(is_superuser=True):
        profile, _ = UserProfile.objects.get_or_create(user=u)
        profile.role = "ADMIN"
        # Give admins the top tier by default.
        if getattr(profile, "subscription_tier", None) in (None, ""):
            profile.subscription_tier = "PLATINUM"
        profile.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_userprofile_subscription_tier"),
    ]

    operations = [
        migrations.RunPython(set_admin_role_for_superusers, migrations.RunPython.noop),
    ]

