# Generated by GPT-5.2 on 2026-01-21

from django.db import migrations, models


def enable_admin_subscriptions(apps, schema_editor):
    UserProfile = apps.get_model("core", "UserProfile")
    UserProfile.objects.filter(role="ADMIN").update(subscription_active=True)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_admin_role_for_superusers"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="subscription_active",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(enable_admin_subscriptions, migrations.RunPython.noop),
    ]

