# Generated by Django 6.0 on 2026-01-21 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_userprofile_subscription_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='execution_time',
            field=models.TimeField(blank=True, help_text='Hora diaria para ejecutar el workflow de reportes (formato HH:MM)', null=True),
        ),
    ]
