# Generated by Django 6.0 on 2026-01-21 21:07

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_execution_time_to_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_phone', models.CharField(db_index=True, help_text='Número de teléfono de la orden', max_length=50)),
                ('order_id', models.CharField(blank=True, help_text='ID de la orden en Dropi si está disponible', max_length=100, null=True)),
                ('status', models.CharField(choices=[('proximo_a_reportar', 'Próximo a Reportar'), ('reportado', 'Reportado'), ('error', 'Error'), ('no_encontrado', 'No Encontrado'), ('already_has_case', 'Ya Tiene Caso'), ('cannot_generate_yet', 'No Se Puede Generar Aún'), ('in_movement', 'En Movimiento')], default='proximo_a_reportar', max_length=50)),
                ('report_generated', models.BooleanField(default=False, help_text='True si el reporte se generó exitosamente')),
                ('customer_name', models.CharField(blank=True, help_text='Nombre del cliente', max_length=255, null=True)),
                ('product_name', models.TextField(blank=True, help_text='Nombre del producto vinculado a la orden', null=True)),
                ('order_state', models.CharField(blank=True, help_text='Estado actual de la orden en Dropi', max_length=100, null=True)),
                ('next_attempt_time', models.DateTimeField(blank=True, help_text='Próximo intento (para estados que requieren espera)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_reports',
                'indexes': [models.Index(fields=['user', 'order_phone'], name='order_repor_user_id_35b043_idx'), models.Index(fields=['user', 'status'], name='order_repor_user_id_1b566b_idx'), models.Index(fields=['user', 'report_generated'], name='order_repor_user_id_98327c_idx'), models.Index(fields=['order_phone'], name='order_repor_order_p_fc1c49_idx'), models.Index(fields=['next_attempt_time'], name='order_repor_next_at_0f3ed9_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['reportado', 'proximo_a_reportar'])), fields=('user', 'order_phone'), name='unique_active_report_per_order')],
            },
        ),
    ]
