# Generated by Django 5.2.9 on 2026-01-22 04:23

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_order_report_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AlterField(
            model_name='futureevent',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AlterField(
            model_name='marketintelligencelog',
            name='embedding_context',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AlterField(
            model_name='marketplacefeedback',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AlterField(
            model_name='productembedding',
            name='embedding_visual',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1152, null=True),
        ),
        migrations.AlterField(
            model_name='uniqueproductcluster',
            name='visual_centroid',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1152, null=True),
        ),
        migrations.AlterField(
            model_name='uniqueproductcluster',
            name='visual_medoid_1',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1152, null=True),
        ),
        migrations.AlterField(
            model_name='uniqueproductcluster',
            name='visual_medoid_2',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1152, null=True),
        ),
        migrations.AlterField(
            model_name='uniqueproductcluster',
            name='visual_medoid_3',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1152, null=True),
        ),
    ]
