# Generated by Django 6.0 on 2026-01-23 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_category_embedding_alter_futureevent_embedding_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('step1_running', 'Paso 1: Descargando Reportes'), ('step1_completed', 'Paso 1: Completado'), ('step2_running', 'Paso 2: Comparando Reportes'), ('step2_completed', 'Paso 2: Completado'), ('step3_running', 'Paso 3: Reportando CAS'), ('step3_completed', 'Paso 3: Completado'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=50)),
                ('current_message', models.TextField(blank=True, help_text='Mensaje actual del progreso', null=True)),
                ('messages', models.JSONField(default=list, help_text='Lista de mensajes de progreso')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('step1_completed_at', models.DateTimeField(blank=True, null=True)),
                ('step2_completed_at', models.DateTimeField(blank=True, null=True)),
                ('step3_completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflow_progress',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='workflow_pr_user_id_810eed_idx'), models.Index(fields=['user', 'started_at'], name='workflow_pr_user_id_76a060_idx')],
            },
        ),
    ]
