# Generated by Django 6.0 on 2026-01-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_workflow_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(blank=True, default='', max_length=120)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('CLIENT', 'Client')], default='CLIENT', max_length=10)),
                ('subscription_tier', models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], default='BRONZE', max_length=10)),
                ('subscription_active', models.BooleanField(default=False)),
                ('execution_time', models.TimeField(blank=True, help_text='Hora diaria para ejecutar el workflow de reportes (formato HH:MM)', null=True)),
                ('dropi_email', models.EmailField(blank=True, help_text='Email de la cuenta Dropi principal', max_length=255, null=True)),
                ('dropi_password', models.CharField(blank=True, help_text='Password de la cuenta Dropi (string simple, no encriptado)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'unified_users',
                'indexes': [models.Index(fields=['username'], name='unified_use_usernam_1a8df8_idx'), models.Index(fields=['email'], name='unified_use_email_969930_idx'), models.Index(fields=['role', 'subscription_tier'], name='unified_use_role_c6fe54_idx'), models.Index(fields=['subscription_active'], name='unified_use_subscri_6679e6_idx')],
            },
        ),
    ]
